default:
  image: python:3.11

before_script:
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

stages:
  - test
  #todo deploy package to pypi


testing:
  stage: test
  script:
    - pytest --cov=src --cov-report=xml
  artifacts:
    - echo "This is the test stage"
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: /builds/USERNAME/python-devop/tests/report.xml
