default:
  image: python:3.11

before_script:
  - pip install poetry
  - poetry install
  - apt-get update -qq && apt-get install -y -qq fd-find
  - mkdir -p ~/.local/bin
  - export PATH=$PATH:~/.local/bin
  - ln -s $(which fdfind) ~/.local/bin/fd
  - source `poetry env info --path`/bin/activate

stages:
  - test
  #todo deploy package to pypi


pytest:
  stage: test
  script:
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

repotracer:
  stage: test
  script:
    - git fetch origin main
    - echo $(which fd)
    - echo $(which fdfind)
    - fd --help
    - echo "Running repotracer on itself"
    - poetry run repotracer install-repos
    - poetry run repotracer run
  artifacts:
   paths:
      - .repotracer/stats/**/*.png
      - .repotracer/stats/**/*.csv
