default:
  image: python:3.11

before_script:
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

stages:
  - test
  #todo deploy package to pypi


testing:
  stage: test
  script:
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    - echo "This is the test stage"
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

