[package]
name = "repotracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
git2 = "0.13.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = "0.26.0"
grep = "0.3.1"
anyhow = "1.0.79"
